

services:
  backend:
    build: ./backend
    container_name: fastapi-backend
    volumes:
      - ./backend/src:/app/src
    ports:
      - "8000:8000"
      - "8888:8888" 
    env_file:
      - ./backend/.env


  frontend:
    container_name: airo-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    # environment:
    #   - NODE_ENV=production
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
