

services:
  backend:
    build: ./backend
    container_name: fastapi-backend
    volumes:
      - ./backend/src:/app/src
    ports:
      - "8000:8000"
      - "8888:8888" 
    env_file:
      - ./backend/.env


  frontend:
    build: ./frontend
    container_name: airo-frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"

